import os

import psycopg
from psycopg.rows import dict_row
from psycopg.errors import UniqueViolation
from werkzeug.security import generate_password_hash, check_password_hash


def get_connection():
    database_url = os.environ.get("DATABASE_URL")

    if not database_url:
        raise RuntimeError("DATABASE_URL environment variable is required.")

    return psycopg.connect(
        database_url,
        row_factory=dict_row
    )


def init_db():
    conn = get_connection()

    try:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username TEXT NOT NULL UNIQUE,
                email TEXT NOT NULL UNIQUE,
                password_hash TEXT NOT NULL,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                last_login TIMESTAMP
            )
        """)

        conn.execute("""
            CREATE TABLE IF NOT EXISTS certificates (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER NOT NULL UNIQUE,
                certificate_id TEXT NOT NULL UNIQUE,
                issued_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY(user_id) REFERENCES users(id)
            )
        """)

        conn.execute("""
            CREATE TABLE IF NOT EXISTS progress (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER NOT NULL,
                task_id INTEGER NOT NULL,
                question_id INTEGER NOT NULL,
                completed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                UNIQUE(user_id, task_id, question_id),
                FOREIGN KEY(user_id) REFERENCES users(id)
            )
        """)

        conn.commit()

    finally:
        conn.close()


def create_user(username, email, password):
    password_hash = generate_password_hash(password)
    conn = get_connection()

    try:
        row = conn.execute(
            """
            INSERT INTO users (username, email, password_hash)
            VALUES (%s, %s, %s)
            RETURNING id
            """,
            (username, email, password_hash)
        ).fetchone()

        conn.commit()
        return row["id"]

    except UniqueViolation:
        conn.rollback()
        return None

    finally:
        conn.close()


def authenticate_user(username, password):
    conn = get_connection()

    try:
        user = conn.execute(
            "SELECT * FROM users WHERE username = %s",
            (username,)
        ).fetchone()

    finally:
        conn.close()

    if user and check_password_hash(user["password_hash"], password):
        return user

    return None


def update_last_login(user_id):
    conn = get_connection()

    try:
        conn.execute(
            """
            UPDATE users
            SET last_login = CURRENT_TIMESTAMP
            WHERE id = %s
            """,
            (user_id,)
        )

        conn.commit()

    finally:
        conn.close()


def mark_question_complete(user_id, task_id, question_id):
    conn = get_connection()

    try:
        conn.execute(
            """
            INSERT INTO progress (user_id, task_id, question_id)
            VALUES (%s, %s, %s)
            ON CONFLICT (user_id, task_id, question_id)
            DO NOTHING
            """,
            (user_id, task_id, question_id)
        )

        conn.commit()

    finally:
        conn.close()


def get_completed_questions(user_id, task_id=None):
    conn = get_connection()

    try:
        if task_id is None:
            rows = conn.execute(
                """
                SELECT task_id, question_id
                FROM progress
                WHERE user_id = %s
                """,
                (user_id,)
            ).fetchall()

        else:
            rows = conn.execute(
                """
                SELECT task_id, question_id
                FROM progress
                WHERE user_id = %s AND task_id = %s
                """,
                (user_id, task_id)
            ).fetchall()

        return rows

    finally:
        conn.close()


def get_certificate(user_id):
    conn = get_connection()

    try:
        row = conn.execute(
            """
            SELECT certificate_id, issued_at
            FROM certificates
            WHERE user_id = %s
            """,
            (user_id,)
        ).fetchone()

        return row

    finally:
        conn.close()


def create_certificate(user_id, certificate_id):
    conn = get_connection()

    try:
        conn.execute(
            """
            INSERT INTO certificates (user_id, certificate_id)
            VALUES (%s, %s)
            ON CONFLICT (user_id)
            DO NOTHING
            """,
            (user_id, certificate_id)
        )

        conn.commit()

        row = conn.execute(
            """
            SELECT certificate_id, issued_at
            FROM certificates
            WHERE user_id = %s
            """,
            (user_id,)
        ).fetchone()

        return row

    finally:
        conn.close()


def get_certificate_by_id(certificate_id):
    conn = get_connection()

    try:
        row = conn.execute(
            """
            SELECT
                certificates.certificate_id,
                certificates.issued_at,
                users.username
            FROM certificates
            JOIN users ON users.id = certificates.user_id
            WHERE certificates.certificate_id = %s
            """,
            (certificate_id,)
        ).fetchone()

        return row

    finally:
        conn.close()
